import runtimeSource from './mermaid-runtime.js?raw';

export function isMermaidContent(text) {
  return /^\s*(?:```mermaid\b|(?:graph|flowchart|sequenceDiagram|classDiagram|stateDiagram(?:-v2)?|erDiagram|journey|gantt|pie|gitGraph|mindmap|quadrantChart|sankey-beta|requirementDiagram|xychart-beta|block-beta|packet-beta|architecture-beta|kanban)\b)/i.test(text);
}


export function buildMermaidPreview(content) {
  const source = JSON.stringify(content).replace(/</g, '\\u003c');
  const icon = path => `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2">${path}</svg>`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mermaid 预览</title><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:white;color:#334155;font:14px system-ui}#diagram{position:absolute;left:0;top:0;width:max-content;cursor:grab;touch-action:none}#diagram svg{display:block}#diagram text,#diagram tspan,#diagram foreignObject{cursor:text;user-select:text}#diagram.dragging,#diagram.dragging *{cursor:grabbing!important;user-select:none}#toolbar{position:fixed;left:50%;transform:translateX(-50%);top:16px;display:flex;align-items:center;gap:8px;padding:6px;background:rgba(255,255,255,.55);backdrop-filter:blur(12px);border:1px solid rgba(148,163,184,.35);border-radius:10px;z-index:10}#toolbar[hidden],#minimap[hidden]{display:none}button{display:grid;place-items:center;width:32px;height:32px;border:0;border-radius:6px;background:rgba(241,245,249,.4);color:#334155;cursor:pointer}button:hover{background:rgba(226,232,240,.6)}#status{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);margin:0;max-width:90vw;max-height:80vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;pointer-events:none}#status:empty{display:none}#zoom{width:76px;border:0;border-radius:6px;padding:6px;background:transparent;color:inherit;cursor:pointer}#minimap{position:fixed;right:16px;bottom:16px;width:300px;height:200px;background:rgba(255,255,255,.7);backdrop-filter:blur(10px);box-shadow:0 2px 12px #0002;border-radius:8px;overflow:hidden;z-index:9;pointer-events:none}#map-image,#map-viewport{position:absolute}#map-image{object-fit:fill}#map-viewport{box-sizing:border-box;border:2px solid #1677ff;background:rgba(22,119,255,.08)}.spinner{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}body{cursor:grab;touch-action:none}body.dragging,body.dragging *{cursor:grabbing!important;user-select:none}#map-viewport{pointer-events:auto;cursor:grab;touch-action:none;user-select:none}#map-viewport.dragging{cursor:grabbing}
</style></head><body><nav id="toolbar" aria-label="图表工具"><button id="copy" title="复制图片" aria-label="复制图片">${icon('<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>')}</button><button id="minus" title="缩小 20%" aria-label="缩小">${icon('<path d="M5 12h14"/>')}</button><select id="zoom" aria-label="缩放比例"><option value="50">50%</option><option value="100" selected>100%</option><option value="150">150%</option><option value="200">200%</option><option value="300">300%</option></select><button id="plus" title="放大 20%" aria-label="放大">${icon('<path d="M5 12h14M12 5v14"/>')}</button></nav><main id="diagram"></main><aside id="minimap" hidden aria-label="图表缩略导航"><img id="map-image" alt=""><div id="map-viewport"></div></aside><p id="status" role="status">正在加载图表…</p><script type="module">(${runtimeSource})(${source});</script></body></html>`;
}
